apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  name: {{ include "nginx.fullname" . }}
  namespace: "{{ .Values.namespace }}"
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }} 
