{
 "title": "NGINX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "NGINX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX UP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_up" },
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "HTTP Requerst Total ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_http_requests_total" }
   ]
  },
  {
   "title": "NGINX Exporter Info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginxexporter_build_info" }
   ]
  },
  {
   "title": "Nginx Connection read/write/wait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_reading" },
    { "expr": "nginx_connections_writing" },
    { "expr": "nginx_connections_waiting" }
   ]
  }
 ]
}